[project]
name = "phue"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.124.2",
    "numpy>=2.3.5",
    "opencv-python>=4.11.0.86",
    "pillow>=10.2.0",
    "ultralytics>=8.3.234",
]
